# Generated by Django 4.1.3 on 2022-12-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500, null=True, verbose_name='Логин')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='ФИО')),
                ('age', models.IntegerField(null=True, verbose_name='Ваш возраст')),
                ('skills', models.TextField(max_length=500, null=True, verbose_name='Ваши навыки')),
                ('job_places', models.TextField(max_length=500, null=True, verbose_name='Предыдущая работа')),
                ('money', models.IntegerField(null=True, verbose_name='Зарплатные ожидания')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
